### ISSUE TITLE
#define pg_strdup       _strdup

### ISSUE THREAD

**Issue by jboakye** [postgresql-interfaces/psqlodbc#15]
symbol lookup error: /usr/local/lib/psqlodbca.so: undefined symbol: _strdup
[Debian][psqlodbc Release 16_004]

**Comment by davecramer** [comment]
You should report this to the debian maintainer.

**Comment by jboakye** [comment]
Just curious though why not define it as strdup ... that's my workaround.

**Comment by df7cb** [comment]
Hi,

anything in `/usr/local` is not a Debian problem. That's something you compiled yourself and installed there.

**Comment by df7cb** [comment]
The Debian package build has the same problem, though:
```
ODBCSYSINI=. ODBCINSTINI=./odbcinst.ini ODBCINI=./odbc.ini ./reset-db < ./sampletables.sql
./reset-db: symbol lookup error: ../.libs/psqlodbcw.so: undefined symbol: _strdup
make[2]: *** [Makefile:32: installcheck] Error 127
```

Full build log: https://pgdgbuild.dus.dg-i.net/job/psqlodbc-binaries/83/architecture=amd64,distribution=sid/console

**Comment by jboakye** [comment]
I just did some research and it seems _strdup is targeted at MS windows? .. seems like the enclosing #ifdefs should make sure _strdup does not get defined for non MS systems. 
Thank you all for looking into it.

**Comment by davecramer** [comment]
enclosing `#ifdefs` ?  We can add that to the official code if you can provide the code.

**Comment by apgrucza** [comment]
Prior to #6, psqlODBC only used `_strdup` on Windows builds. `_strdup` is actually part of ISO C and C++, but as it does not compile on all systems, I've created #17 to resolve this issue.

**Comment by df7cb** [comment]
@davecramer do you plan a new release with the fix?

**Comment by davecramer** [comment]
I'd like to make sure some other things are fixed first, but sure.
