### ISSUE TITLE
Plan to implement SQLSetDescRec & SQLGetDescRec functions

### ISSUE THREAD

**Issue by Hunaid2000** [postgresql-interfaces/psqlodbc#21]
Currently, psqlodbc lacks support for SQLSetDescRec and SQLGetDescRec functions. Any idea why these functions are not implemented yet? 

I plan to implement these functions and will open a PR in few days. Any ideas or suggestions regarding the implementation would be greatly appreciated.

**Comment by davecramer** [comment]
@Hunaid2000 no idea. We are taking this project over. The previous maintainers have resigned. 

We are of course open to PR's Thanks in advance
