### ISSUE TITLE
It seems 32bit driver does not have ssl compiled in ?

### ISSUE THREAD

**Issue by musashi-garami** [postgresql-interfaces/psqlodbc#26]
I'm not 100% sure, although I've tested many setups.

64bit driver works 100%, connects with SSL (seems to ignore when I try add the cert path in my connection string, it looks like it's hardcoded to look C:\Users\<user>\AppData\Roaming\postgresql\root.crt - this is fine, if I put the root cert there it works.

I was setting up on another pc, with 32bit MS ACCESS (the frontend connecting to my postgres backend). And it would not work at all, when trying to create the DSN, (32bit) I get a message saying SSL not compiled in. 

64bit works in the ODBC manager, creating DSN's. It also works with MS access in my connection string (as long as I put the certificate in the hard coded location).

32bit doesn't seem to work with SSL, so I suspect 2 things:

1) The hard coded path that 32bit is searching for root cert is different and I don't know what it is
2) 32bit compiled psqlodbc driver does not have ssl compiled in (I suspect it's this).

I'm not an expert in this area, and could be wrong in my understanding, but from a lot of testing, this seems to be the conclusion.

**Comment by RegisHubelia** [comment]
+1

**Comment by musashi-garami** [comment]
This is fixed in REL-16_00_0005

https://github.com/postgresql-interfaces/psqlodbc/releases/tag/REL-16_00_0005

Thank you @davecramer
