### ISSUE TITLE
17.0.1 MSIs contain version 17.0.0

### ISSUE THREAD

**Issue by chrullrich** [postgresql-interfaces/psqlodbc#56]
The 17.0.1 MSIs have version 17.0.0 both in the ProductVersion property (so they will fail to upgrade from the 17.0.0 MSIs) and in the file versions of the versioned DLLs.

The code change from ab76a10c appears to be present in the DLLs; the largest difference between the two is in the function that was changed there.

![image](https://github.com/user-attachments/assets/62e39ec1-f2c6-47ec-bff7-10a08314f316)

![image](https://github.com/user-attachments/assets/b6858a43-2ce0-4576-8011-f2f533bf7a14)

**Comment by davecramer** [comment]
Dang, I missed that. Thanks I'll fix it
